### ISSUE TITLE
LineBreakBetweenFunctionsSniff.php asks for line breaks in PHP match statements

### ISSUE THREAD

**Issue by ladbsoft** [PcComponentes/coding-standard#22]
In match statements like follows:

```php
return match ($contentType->value()) {
    ContentType::fromCsv()->value() => $this->csvReceptionFileReaderStrategy,
    default => $this->csvReceptionFileReaderStrategy,
};
```

An error `There must be exactly 1 line break after a function.` is given:

![imagen](https://user-images.githubusercontent.com/30509719/207887017-f0ca7640-95d4-4c5e-83b3-76f19bcd1af2.png)

And PHPCBF fixes it like follows:

```php
return match ($contentType->value()) {
    ContentType::fromCsv()->value() => $this->csvReceptionFileReaderStrategy,
    default => $this->csvReceptionFileReaderStrategy,
}

;
```

This validation is made in https://github.com/PcComponentes/coding-standard/blob/master/src/Sniffs/ControlStructures/LineBreakBetweenFunctionsSniff.php

We should fix this, since the line breaks are not needed here

**Comment by ladbsoft** [comment]
This leads to a validation loop in cases of using the match statement inside an arrow function:

This:
```php
static fn (ArticleId $articleId) => match ($articleId->value()) {
    $heavyArticleId1 => $heavyArticle1,
    $heavyArticleId2 => $heavyArticle2,
    default => throw new ExpectationFailedException('Unexpected Article Id'),
},
```

Gives validation error:
![imagen](https://github.com/PcComponentes/coding-standard/assets/30509719/6354a7bc-5a5f-4352-b3f0-eb013d78940a)

The fix according to this rule should be:
```php
static fn (ArticleId $articleId) => match ($articleId->value()) {
    $heavyArticleId1 => $heavyArticle1,
    $heavyArticleId2 => $heavyArticle2,
    default => throw new ExpectationFailedException('Unexpected Article Id'),
}

,
```

But this leads to another two validation errors:
![imagen](https://github.com/PcComponentes/coding-standard/assets/30509719/c83eed34-43be-487b-937a-27bedf9f5ff3)

PHPCBF does not fix this:

![imagen](https://github.com/PcComponentes/coding-standard/assets/30509719/1d13c80d-5e99-4c06-9bbc-1f664dd62c57)

**Comment by zoilomora** [comment]
@ladbsoft can you check if it is already resolved?

**Comment by ladbsoft** [comment]
@zoilomora it totally seems it does! Thanks so much! ❤️
